version: '3.7'

x-env-defaults: &env
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:12.15-alpine
  working_dir: /mc
  restart: always
  volumes:
    - .:/mc:cached
    - ./node_modules:/mc/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  email-export:
    <<: *node
    working_dir: /mc/services/email-export
    entrypoint: ["/bin/sh"]
    environment:
      <<: *env
      GRAPHQL_URL: http://graphql
      EMAIL_EXPORT_MONGO_DSN: ${EMAIL_EXPORT_MONGO_DSN-}
    depends_on:
      - graphql

  graphql:
    <<: *node
    working_dir: /mc/services/graphql
    entrypoint: ["node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 17430
      FUEL_API_CLIENT_ID: ${FUEL_API_CLIENT_ID}
      FUEL_API_CLIENT_SECRET: ${FUEL_API_CLIENT_SECRET}
      FUEL_API_AUTH_URL: ${FUEL_API_AUTH_URL}
      FUEL_API_ACCOUNT_ID: ${FUEL_API_ACCOUNT_ID}
      TERMINUS_TIMEOUT: 1000
      TERMINUS_SHUTDOWN_DELAY: 0
    ports:
      - "17430:80"

volumes:
  yarn-cache: {}
